services:
  - type: web
    name: funko-battle
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///funko_battle.db
      - key: TELEGRAM_BOT_TOKEN
        sync: false
