services:
  - type: web
    name: funko-battle
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    databases:
      - name: funko_battle_db
        databaseName: funko_battle
        user: funko_battle
